version: 2
workflows:
  version: 2
  default:
    jobs:
      - build
      - release
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: mbgl/ci@sha256:c34e221294d81da80918d3e9a9df5de795b067e88f86d7c9a5e262763332536e
    environment:
      JVM_OPTS: -Xmx3200m
      BUILDTYPE: Debug
      IS_LOCAL_DEVELOPMENT: false
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}
      - run:
          name: Check Java code style
          command: make checkstyle
      - run:
          name: Jacoco test report
          command: ./gradlew jacocoTestReport
      - run:
          name: Run unit-test for all modules
          command: make test
      - run:
          name: SonarQube upload
          command: make sonarqube
      - run:
          name: Update Transifex
          command: |
            if [ "${CIRCLE_BRANCH}" == "${DEPLOY_BRANCH}" ]; then
              pip install transifex-client
              echo $'[https://www.transifex.com]\nhostname = https://www.transifex.com\nusername = '"${TRANSIFEX_USER}"$'\npassword = '"${TRANSIFEX_API_TOKEN}"$'\ntoken = '""$'\n' > ~/.transifexrc
              tx push -s
            else
              echo "Skipping push to Transifex"
            fi
      - store_artifacts:
          path: mapbox/app/build/reports
          destination: reports
      - store_test_results:
          path: mapbox/app/build/test-results

# ------------------------------------------------------------------------------
  release:
    branch:
      only:
      - master
    docker:
      - image: mbgl/ci@sha256:c34e221294d81da80918d3e9a9df5de795b067e88f86d7c9a5e262763332536e
    working_directory: ~/code
    environment:
    environment:
      BUILDTYPE: Release
      IS_LOCAL_DEVELOPMENT: false
    steps:
      - checkout
      - run:
          name: Accept Android license
          command: |
           echo y | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;26.0.1"
      - run:
          name: Generate Maven credentials
          shell: /bin/bash -euo pipefail
          command: |
            aws s3 cp s3://mapbox/android/signing-credentials/secring.gpg secring.gpg
            echo "NEXUS_USERNAME=$PUBLISH_NEXUS_USERNAME
            NEXUS_PASSWORD=$PUBLISH_NEXUS_PASSWORD
            signing.keyId=$SIGNING_KEYID
            signing.password=$SIGNING_PASSWORD
            signing.secretKeyRingFile=../secring.gpg" >> gradle.properties
      - run:
          name: Build Java libraries
          command: make build-release
      - deploy:
          name: Publish Java Services To Maven Central
          command: |
            if [ "${CIRCLE_BRANCH}" == "mb-java-3.0.0" ]; then
            make publish ;
            fi