version: 2
workflows:
  version: 2
  default:
    jobs:
      - build
      - test
      - release-snapshot:
          requires:
            - build
            - test
          filters:
            branches:
              only:
                - master
      - release:
          requires:
            - build
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

jobs:
  build:
    working_directory: ~/code
    docker:
      - image: mbgl/android-ndk-r19:latest
    steps:
      - checkout
      - run:
          name: Build libraries
          command: make build-release
      - run:
          name: Build command line interface
          command: make build-cli

  test:
    working_directory: ~/code
    docker:
      - image: mbgl/android-ndk-r19:latest
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}
      - run:
          name: Check Java code style
          command: make checkstyle
      - run:
          name: Jacoco test report
          command: ./gradlew jacocoTestReport
      - run:
          name: Run unit-test for all modules
          command: make test
      - store_artifacts:
          path: mapbox/app/build/reports
          destination: reports
      - store_test_results:
          path: mapbox/app/build/test-results    
      - run:
          name: Post code coverage report to Codecov.io
          command: |
            bash <(curl -s https://codecov.io/bash)

# ------------------------------------------------------------------------------
  release-snapshot:
    docker:
      - image: mbgl/android-ndk-r19:latest
    working_directory: ~/code
    steps:
      - checkout
      - deploy:
          name: Publish Java snapshot libraries to Mapbox SDK Registry
          command: |
            make sdk-registry-publish-snapshot

  release:
    docker:
      - image: mbgl/android-ndk-r19:latest
    working_directory: ~/code
    steps:
      - checkout
      - deploy:
          name: Publish Java libraries to Mapbox SDK Registry
          command: |
            make sdk-registry-publish
