version: 2.1
workflows:
  version: 2
  release-workflow:
    jobs:
      - release:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
  default:
    jobs:
      - build
      - test
      - publish-snapshot:
          requires:
            - build
            - test
          filters:
            branches:
              only:
                - master

commands:
  build-release:
    steps:
      - run:
          name: Build libraries
          command: make build-release

  build-cli:
    steps:
      - run:
          name: Build command line interface
          command: make build-cli

  run-tests:
    steps:
      - run:
          name: Check Java code style
          command: make checkstyle
      - run:
          name: Jacoco test report
          command: ./gradlew jacocoTestReport
      - run:
          name: Run unit-test for all modules
          command: make test
      - store_artifacts:
          path: mapbox/app/build/reports
          destination: reports
      - store_test_results:
          path: mapbox/app/build/test-results
      - run:
          name: Post code coverage report to Codecov.io
          command: |
            bash <(curl -s https://codecov.io/bash)

jobs:
  build:
    working_directory: ~/code
    docker:
      - image: mbgl/android-ndk-r19:latest
    steps:
      - checkout
      - build-release
      - build-cli

  test:
    working_directory: ~/code
    docker:
      - image: mbgl/android-ndk-r19:latest
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}
      - run-tests

# ------------------------------------------------------------------------------
  publish-snapshot:
    docker:
      - image: mbgl/android-ndk-r19:latest
    working_directory: ~/code
    steps:
      - checkout
      - deploy:
          name: Publish Java snapshot libraries to Mapbox SDK Registry
          command: |
            make sdk-registry-publish-snapshot

  release:
    docker:
      - image: mbgl/android-ndk-r19:latest
    working_directory: ~/code
    steps:
      - checkout
      - build-release
      - build-cli
      - run-tests
      - deploy:
          name: Upload libraries to Mapbox SDK Registry
          command: |
            make sdk-registry-upload
#      This is not yet supported, still need to be able to authenticate CI to create a Github pull request.
#      - run:
#          name: Create pull request in api-downloads
#          command: |
#            make sdk-registry-publish
